module.exports = Object.freeze({
  USER_FULL: 'User Full Access',
  PUBLIC_FULL: 'Public Full Access',
  CUSTOMER_FULL: 'Customer Full Access',
  CATEGORY_FULL: 'Category Full Access',
  UOM_FULL: 'UoM Full Access',
  BRAND_FULL: 'Brand Full Access',
  WAREHOUSE_FULL: 'Warehouse Full Access',
  PRODUCT_FULL: 'Product Full Access',
  PRODUCTINWARD_FULL: 'Product Inward Full Access',
  DISPATCHORDER_FULL: 'Dispatch Order Full Access',
  PRODUCTOUTWARD_FULL: 'Product Outward Full Access',
  INVENTORY_FULL: 'Inventory Full Access',
  CUSTOMERINQUIRY_FULL: 'Customer Inquiry Full Access',
  USER_READ: 'User Read Access',
  PUBLIC_READ: 'Public Read Access',
  CUSTOMER_READ: 'Customer Read Access',
  CATEGORY_READ: 'Category Read Access',
  UOM_READ: 'UoM Read Access',
  BRAND_READ: 'Brand Read Access',
  WAREHOUSE_READ: 'Warehouse Read Access',
  PRODUCT_READ: 'Product Read Access',
  PRODUCTINWARD_READ: 'Product Inward Read Access',
  DISPATCHORDER_READ: 'Dispatch Order Read Access',
  PRODUCTOUTWARD_READ: 'Product Outward Read Access',
  INVENTORY_READ: 'Inventory Read Access',
  CUSTOMERINQUIRY_READ: 'Customer Inquiry Read Access'
});
