module.exports = {
  AdjustmentInventory: require("./AdjustmentInventory"),
  StockAdjustment: require("./StockAdjustment"),
  Company: require("./Company"),
  Inventory: require("./Inventory"),
  Warehouse: require("./Warehouse"),
  Product: require("./Product"),
  WastagesType: require("./WastagesType"),
  ActivityLog: require("./ActivityLog"),
  Car: require("./Car"),
  CarMake: require("./CarMake"),
  CarModel: require("./CarModel"),
  VehicleType: require("./VehicleType"),
  UOM: require("./UOM"),
  Brand: require("./Brand"),
  Category: require("./Category"),
  DispatchOrder: require("./DispatchOrder"),
  ProductOutward: require("./ProductOutward"),
  OrderGroup: require("./OrderGroup"),
  OutwardGroup: require("./OutwardGroup"),
  Vehicle: require("./Vehicle"),
  Ride: require("./Ride"),
  ActivitySourceType: require("./ActivitySourceType"),
};
